alt_login: 'off'
auth_instructions: 'Utilizzare <a href="http://localhost/moodle_testing/auth/shibboleth/index.php">Shibboleth login</a> per avere accesso tramite Shibboleth, se l''organizzazione lo supporta<br />Altrimenti, utilizzare il modulo di login standard visualizzato.'
auth_logo: ''
changepasswordurl: ''
convert_data: ''
field_lock_address: unlocked
field_lock_alternatename: unlocked
field_lock_city: unlocked
field_lock_country: unlocked
field_lock_department: unlocked
field_lock_description: unlocked
field_lock_email: unlocked
field_lock_firstname: unlocked
field_lock_firstnamephonetic: unlocked
field_lock_idnumber: unlocked
field_lock_institution: unlocked
field_lock_lang: unlocked
field_lock_lastname: unlocked
field_lock_lastnamephonetic: unlocked
field_lock_middlename: unlocked
field_lock_phone1: unlocked
field_lock_phone2: unlocked
field_map_address: ''
field_map_alternatename: ''
field_map_city: ''
field_map_country: ''
field_map_department: ''
field_map_description: ''
field_map_email: ''
field_map_firstname: ''
field_map_firstnamephonetic: ''
field_map_idnumber: ''
field_map_institution: ''
field_map_lang: ''
field_map_lastname: ''
field_map_lastnamephonetic: ''
field_map_middlename: ''
field_map_phone1: ''
field_map_phone2: ''
field_updatelocal_address: oncreate
field_updatelocal_alternatename: oncreate
field_updatelocal_city: oncreate
field_updatelocal_country: oncreate
field_updatelocal_department: oncreate
field_updatelocal_description: oncreate
field_updatelocal_email: oncreate
field_updatelocal_firstname: oncreate
field_updatelocal_firstnamephonetic: oncreate
field_updatelocal_idnumber: oncreate
field_updatelocal_institution: oncreate
field_updatelocal_lang: oncreate
field_updatelocal_lastname: oncreate
field_updatelocal_lastnamephonetic: oncreate
field_updatelocal_middlename: oncreate
field_updatelocal_phone1: oncreate
field_updatelocal_phone2: oncreate
login_name: 'Shibboleth Login'
logout_handler: ''
logout_return_url: ''
organization_selection: "urn:mace:organization1:providerID, Example Organization 1\n        https://another.idp-id.com/shibboleth, Other Example Organization, /Shibboleth.sso/DS/SWITCHaai\n        urn:mace:organization2:providerID, Example Organization 2, /Shibboleth.sso/WAYF/SWITCHaai"
user_attribute: ''
version: '2022112800'
