config_decimalpoints: '2'
config_decimalpoints_locked: ''
config_gradeformat: '1'
config_gradeformat_locked: ''
config_nameformat: '1'
config_nameformat_locked: ''
config_showbest: '3'
config_showbest_locked: ''
config_showworst: '0'
config_showworst_locked: ''
config_usegroups: '0'
config_usegroups_locked: ''
version: '2022112800'
