customfiltergrouping: ''
displaycategories: '1'
displaygroupingall: '1'
displaygroupingallincludinghidden: '0'
displaygroupingcustomfield: '0'
displaygroupingfavourites: '1'
displaygroupingfuture: '1'
displaygroupinghidden: '1'
displaygroupinginprogress: '1'
displaygroupingpast: '1'
layouts: 'card,list,summary'
version: '2022112800'
