dbencoding: utf-8
dbhost: localhost
dbname: ''
dbpass: ''
dbsetupsql: ''
dbsybasequoting: '0'
dbtype: ''
dbuser: ''
debugdb: '0'
defaultcategory: '1'
defaultrole: '5'
ignorehiddencourses: '0'
localcategoryfield: id
localcoursefield: idnumber
localrolefield: shortname
localuserfield: idnumber
newcoursecategory: ''
newcoursefullname: fullname
newcourseidnumber: idnumber
newcourseshortname: shortname
newcoursetable: ''
remotecoursefield: ''
remoteenroltable: ''
remoteotheruserfield: ''
remoterolefield: ''
remoteuserfield: ''
templatecourse: ''
unenrolaction: '0'
version: '2022112800'
