encoding: UTF-8
expiredaction: '3'
location: ''
mailadmins: '0'
mailstudents: '0'
mailteachers: '0'
map_1: manager
map_2: coursecreator
map_3: editingteacher
map_4: teacher
map_5: student
map_6: guest
map_7: user
map_8: frontpage
unenrolaction: '3'
version: '2022112800'
