categoryidnumber: '0'
categoryseparator: ''
createnewcategories: '0'
createnewcourses: '0'
createnewusers: '0'
fixcasepersonalnames: '0'
fixcaseusernames: '0'
imscapitafix: '0'
imscoursemapfullname: short
imscoursemapshortname: coursecode
imscoursemapsummary: ignore
imsdeleteusers: '0'
imsfilelocation: ''
imsrestricttarget: ''
imsrolemap01: '5'
imsrolemap02: '3'
imsrolemap03: '3'
imsrolemap04: '5'
imsrolemap05: '0'
imsrolemap06: '4'
imsrolemap07: '0'
imsrolemap08: '4'
imssourcedidfallback: '0'
imsunenrol: '0'
imsupdateusers: '0'
logtolocation: ''
mailadmins: '0'
nestedcategories: '0'
truncatecoursecodes: '0'
unenrolaction: '0'
updatecourses: '0'
version: '2022112800'
