defaultenrol: '1'
enrolperiod: '0'
expiredaction: '1'
expirynotify: '0'
expirynotifyhour: '6'
expirythreshold: '86400'
groupkey: '0'
longtimenosee: '0'
maxenrolled: '0'
newenrols: '1'
requirepassword: '0'
roleid: '5'
sendcoursewelcomemessage: '1'
showhint: '0'
status: '1'
usepasswordpolicy: '0'
version: '2022112800'
