buffersize: '50'
dbcollation: ''
dbdriver: ''
dbhandlesoptions: '0'
dbhost: ''
dbname: ''
dbpass: ''
dbpersist: '0'
dbport: ''
dbschema: ''
dbsocket: ''
dbtable: ''
dbuser: ''
includeactions: 'c,r,u,d'
includelevels: '1,2,0'
jsonformat: '1'
logguests: '0'
version: '2022112800'
