activitylink: ''
activitylink_adv: '1'
customscoring: '1'
customscoring_adv: '1'
defaultfeedback: '0'
defaultfeedback_adv: '1'
defaultnextpage: '0'
defaultnextpage_adv: '1'
displayleftif: '0'
displayleftif_adv: '1'
displayleftmenu: '0'
displayleftmenu_adv: ''
displayreview: '0'
displayreview_adv: ''
handlingofretakes: '0'
handlingofretakes_adv: '1'
maxanswers: '5'
maxanswers_adv: '1'
maximumnumberofattempts: '1'
maximumnumberofattempts_adv: ''
mediaclose: '0'
mediafile: ''
mediafile_adv: '1'
mediaheight: '480'
mediawidth: '640'
minimumnumberofquestions: '0'
minimumnumberofquestions_adv: '1'
modattempts: '0'
modattempts_adv: ''
numberofpagestoshow: '1'
numberofpagestoshow_adv: '1'
ongoing: '0'
ongoing_adv: '1'
password: '0'
password_adv: '1'
practice: '0'
practice_adv: ''
progressbar: '0'
progressbar_adv: ''
retakesallowed: '0'
retakesallowed_adv: ''
slideshow: '0'
slideshow_adv: '1'
slideshowbgcolor: '#FFFFFF'
slideshowheight: '480'
slideshowwidth: '640'
timelimit: '0'
timelimit_adv: ''
version: '2022112800'
