androidappid: com.moodle.moodlemobile
apppolicy: ''
autologinmintimebetweenreq: '360'
customlangstrings: ''
custommenuitems: ''
disabledfeatures: ''
enablesmartappbanners: '0'
filetypeexclusionlist: ''
forcedurlscheme: moodlemobile
forcelogout: '0'
iosappid: '633359593'
minimumversion: ''
qrcodetype: '1'
qrkeyttl: '600'
qrsameipcheck: '1'
setuplink: 'https://download.moodle.org/mobile'
typeoflogin: '1'
version: '2022112800'
